Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Style/CaseEquality:
  Enabled: false

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/bundle'
    - 'db/schema.rb'
  SuggestExtensions:
    rubocop-rails: false
